---
- name: Install Grafana
  hosts: grafana-bench
  become: yes
  vars:
    victorialogs_datasource_version: 0.2.6
    victoriametrics_datasource_ver: 0.1.3
  
  tasks:
    - name: Install required packages 
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - adduser
        - libfontconfig1

    - name: Download Grafana deb package
      get_url:
        url: https://dl.grafana.com/oss/release/grafana_10.0.3_amd64.deb
        dest: /tmp/grafana_10.0.3_amd64.deb

    - name: Install Grafana deb package
      apt:
        deb: /tmp/grafana_10.0.3_amd64.deb
        state: present
      
    - name: Grafana configuration file
      template:
        src: templates/grafana-config.j2
        dest: /etc/grafana/grafana.ini

    - name: Ensure plugins directory exists
      ansible.builtin.file:
        path: /var/lib/grafana/plugins
        state: directory

    - name: Download victorialogs-datasource plugin
      get_url:
        url: "https://github.com/VictoriaMetrics/victorialogs-datasource/releases/download/v{{ victorialogs_datasource_version }}/victorialogs-datasource-v{{ victorialogs_datasource_version }}.tar.gz"
        dest: "/var/lib/grafana/plugins/victorialogs-datasource-v{{ victorialogs_datasource_version }}.tar.gz"

    - name: Extract victorialogs-datasource plugin
      ansible.builtin.unarchive:
        src: "/var/lib/grafana/plugins/victorialogs-datasource-v{{ victorialogs_datasource_version }}.tar.gz"
        dest: "/var/lib/grafana/plugins"
        remote_src: yes
        creates: "/var/lib/grafana/plugins/victorialogs-datasource"

    - name: Restart Grafana service
      ansible.builtin.service:
        name: grafana-server
        state: restarted
        enabled: yes

    - name: Download VictoriaMetrics Grafana datasource plugin
      get_url:
        url: "https://github.com/VictoriaMetrics/grafana-datasource/releases/download/v{{ victoriametrics_datasource_ver}}/victoriametrics-datasource-v{{ victoriametrics_datasource_ver}}.tar.gz"
        dest: "/var/lib/grafana/plugins/plugin.tar.gz"

    - name: Extract plugin archive
      ansible.builtin.command: tar -xf /var/lib/grafana/plugins/plugin.tar.gz -C /var/lib/grafana/plugins/
      args:
        creates: "/var/lib/grafana/plugins/victoriametrics-datasource"

    - name: Remove downloaded plugin archive
      ansible.builtin.file:
        path: /var/lib/grafana/plugins/plugin.tar.gz
        state: absent